### ISSUE TITLE
Extract Obal CLI core to separate library

### ISSUE THREAD

**Issue by ehelms** [theforeman/obal#171]
Inspired by work started here (https://github.com/theforeman/forklift/pull/911), I felt it better to have the general discussion on Obal itself.

There is an abstraction within Obal for creating a CLI around Ansible playbooks, roles and modules. The idea would be to extract that logic to a newly named Python project that Obal depends on and other projects could use.

 1) Does this make sense?
 2) What should the new project be named?

**Comment by evgeni** [comment]
1. yes as we'd like to re-use the overall layout for other tooling in foreman
2. Given "obal" means packaging or wrapping in Czech, my initial thought was "what's content (as it goes INSIDE a wrapping)?" - according to Google Translate it's "obsah" and I think I like it. But we can also just use obal as a library as it is today without splitting.

**Comment by ehelms** [comment]
I like obsah, sounds unique and maybe easy to pronounce unless I am
butchering it out loud.

I think it muddies what Obal is too much to use it as a library and as a
packaging tool.

**Comment by ekohl** [comment]
Would obal be the library and obsah the packaging playbooks or the other way around?

**Comment by evgeni** [comment]
Given content is inside a package, I'd go with obsah is the library.

**Comment by ekohl** [comment]
You could also say that obsah is wrapping some content so is the actual wrapper. However, we've already established obal as a tool that people know. Extracting something should get a new name. :+1: for obsah as the engine.
