### ISSUE TITLE
diff package fails for packages with epoch

### ISSUE THREAD

**Issue by evgeni** [theforeman/obal#271]
```
'Git version: rubygem-pulpcore_client-1:3.7.1-1.el8'
'Tagged version: rubygem-pulpcore_client-3.7.1-1.el8'
```

**Comment by ehelms** [comment]
Koji does not seem to want to cough up the information on Epoch through it's queries. That seems to leave two options:

 1) Download the source RPM and query it locally
 2) Drop the epoch from the spec file query

**Comment by evgeni** [comment]
I'd avoid downloading things, so let's drop it from the diff package query (but leave it for others)
