### ISSUE TITLE
Apply best practices to the check_build role

### ISSUE THREAD

**Issue by pcreech** [theforeman/obal#37]
tasks/check_build.yml was converted into a role by [this pr](https://github.com/evgeni/obal/pull/33)

The check_build role needs to be refactored to comply with best practices

**Comment by ehelms** [comment]
I would also include in the re-factoring to look at the naming to try to move towards being generic if possible and dropping koji or brew references.

**Comment by evgeni** [comment]
I think this was mostly done in #50 and #69, so I'd consider this issue done.

@pcreech @ehelms whatcha think?

**Comment by pcreech** [comment]
@evgeni Agreed
